let elem = document.querySelectorAll('nav > a')[1];

console.log(elem);
console.log(elem);
console.log(elem);
console.log(elem);
console.log(elem);
console.log(elem);
console.log(elem);
console.log(elem);
console.log(elem);
console.log(elem);
console.log(elem);
console.log(elem);
console.log(elem);
console.log(elem);
console.log(elem);
console.log(elem);
console.log(elem);
console.log(elem);
console.log(elem);
console.log(elem);
console.log(elem);
console.log(elem);
console.log(elem);