name: FTP Deploy

on:
  push:
    branches: [main] # Замените на нужную ветку

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
        
    - name: Deploy to FTP Server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: my.marshib.ru
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: "ftps" # Используйте "sftp" для защищенного соединения
        local-dir: ./